### ISSUE TITLE
Mejorar aspecto de la agenda

### ISSUE THREAD

**Issue by jemonra** [jemonra/CarreraSolidariaPalmones#4]

**Comment by nmlacera** [comment]
Este lo puedo hacer yo, así vemos como trabajar en equipo con GitHub.
Mira si tienes alguna opción para asignarme esta tarea.

**Comment by nmlacera** [comment]
Actividades previas
Desde el 1 de Febrero
o   Entrenamientos colectivos y solidarios
o   Campañas de ayuda con Asociación Familiares Alzheimer Barreño
o   Venta de camisetas a través de nuestra app para ayuda a asociación.
 
Dorsales
Del 13 de abril al 15 Abril 2017
o   Fila 0: Ayuda directa para Asociación Familiares Alzheimer Barreño y venta de camisetas.
 
Día de la Carrera
15 Abril 2017
o   Carrera Absoluta: 10:30
o   Carreras Infantiles: A partir de las 11:30
o   Entrega de Trofeos: 13:00

**Comment by nmlacera** [comment]
Ya puedes cerrar este elemento porque he creado un listview.
Mejor no meterse en pasar el evento a la agenda.
No hace falta complicarse

**Comment by nmlacera** [comment]
Ya la cierro yo
